### ISSUE TITLE
AttributeError: 'list' object has no attribute 'upper'

### ISSUE THREAD

**Issue by maxlcoder** [graysonw/target-bigquery#36]
Hello，

I run 

```
~/.virtualenvs/tap-facebook/bin/tap-facebook --config tap_facebook_config.json -p properties.json | ~/.virtualenvs/target-bigquery/bin/target-bigquery -c target_bigquery_config.json
```

returns

```
INFO Syncing adcreative, fields {'id'}
Traceback (most recent call last):
  File "/Users/akou/.virtualenvs/target-bigquery/bin/target-bigquery", line 8, in <module>
    sys.exit(main())
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/target_bigquery.py", line 300, in main
    state = persist_lines_stream(config['project_id'], config['dataset_id'], input, validate_records=validate_records)
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/target_bigquery.py", line 239, in persist_lines_stream
    tables[table] = bigquery.Table(dataset.table(table), schema=build_schema(schemas[table]))
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/google/cloud/bigquery/table.py", line 344, in __init__
    self.schema = schema
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/google/cloud/bigquery/table.py", line 410, in schema
    self._properties["schema"] = {"fields": _build_schema_resource(value)}
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/google/cloud/bigquery/schema.py", line 289, in _build_schema_resource
    return [field.to_api_repr() for field in fields]
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/google/cloud/bigquery/schema.py", line 289, in <listcomp>
    return [field.to_api_repr() for field in fields]
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/google/cloud/bigquery/schema.py", line 177, in to_api_repr
    answer["fields"] = [f.to_api_repr() for f in self.fields]
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/google/cloud/bigquery/schema.py", line 177, in <listcomp>
    answer["fields"] = [f.to_api_repr() for f in self.fields]
  File "/Users/akou/.virtualenvs/target-bigquery/lib/python3.8/site-packages/google/cloud/bigquery/schema.py", line 170, in to_api_repr
    "type": self.field_type.upper(),
AttributeError: 'list' object has no attribute 'upper'
```

**Comment by ghost** [comment]
I got this using the `tap-stripe`

**Comment by YingWang-Clare** [comment]
I met this issue with tap-facebook as well. I also tried with target-csv and I could successfully get the output file in proper format. Does anyone have any idea to solve?

**Comment by bfirsh** [comment]
Looks like https://github.com/RealSelf/target-bigquery/pull/17 is the fix for this.

**Comment by ednarb29** [comment]
I also got that error and would appreciate it if the fix could be merged.
