### ISSUE TITLE
Target crashes with error `AttributeError: module 'singer' has no attribute 'ActivateVersionMessage'`

### ISSUE THREAD

**Issue by paultiplady** [graysonw/target-bigquery#6]
It looks like there's a version inconsistency in the target; the setup.py specifies `singer-python==1.5.0` (here), but that old version doesn't include `singer.ActivateVersionMessage`.

Fix seems to be to update `singer-python` to a recent version.

**Comment by paultiplady** [comment]
Detailed stacktrace:

```
$ ./load/venv/bin/target-bigquery -c load/config.json < tmpdata.json 
Traceback (most recent call last):
  File "./load/venv/bin/target-bigquery", line 11, in <module>
    sys.exit(main())
  File "/Users/paul/qwil/bi-pipieline/load/venv/lib/python3.6/site-packages/target_bigquery.py", line 285, in main
    state = persist_lines_stream(config['project_id'], config['dataset_id'], input) if config.get('stream_data', True) else persist_lines_job(config['project_id'], config['dataset_id'], input)
  File "/Users/paul/qwil/bi-pipieline/load/venv/lib/python3.6/site-packages/target_bigquery.py", line 158, in persist_lines_job
    elif isinstance(msg, singer.ActivateVersionMessage):
AttributeError: module 'singer' has no attribute 'ActivateVersionMessage'
```

**Comment by paultiplady** [comment]
Fresh venv, Python v3.6.8. Just this package installed.

```
$ pip freeze
backoff==1.3.2
cachetools==3.1.0
certifi==2018.11.29
chardet==3.0.4
dill==0.2.9
future==0.16.0
gapic-google-cloud-datastore-v1==0.15.3
gapic-google-cloud-error-reporting-v1beta1==0.15.3
gapic-google-cloud-logging-v2==0.91.3
google-api-core==0.1.4
google-api-python-client==1.6.2
google-auth==1.6.3
google-cloud==0.32.0
google-cloud-bigquery==0.28.0
google-cloud-bigquery-datatransfer==0.1.1
google-cloud-bigtable==0.28.1
google-cloud-container==0.1.1
google-cloud-core==0.28.1
google-cloud-datastore==1.4.0
google-cloud-dns==0.28.0
google-cloud-error-reporting==0.28.0
google-cloud-firestore==0.28.0
google-cloud-language==1.0.2
google-cloud-logging==1.4.0
google-cloud-monitoring==0.28.1
google-cloud-pubsub==0.30.1
google-cloud-resource-manager==0.28.3
google-cloud-runtimeconfig==0.28.3
google-cloud-spanner==0.29.0
google-cloud-speech==0.30.0
google-cloud-storage==1.6.0
google-cloud-trace==0.17.0
google-cloud-translate==1.3.3
google-cloud-videointelligence==1.0.1
google-cloud-vision==0.29.0
google-gax==0.15.16
google-resumable-media==0.3.2
googleapis-common-protos==1.5.8
grpc-google-iam-v1==0.11.4
grpcio==1.19.0
httplib2==0.12.1
idna==2.8
jsonschema==2.6.0
oauth2client==4.1.3
pendulum==1.2.0
ply==3.8
proto-google-cloud-datastore-v1==0.90.4
proto-google-cloud-error-reporting-v1beta1==0.15.3
proto-google-cloud-logging-v2==0.91.3
protobuf==3.6.1
psutil==5.5.1
pyasn1==0.4.5
pyasn1-modules==0.2.4
python-dateutil==2.8.0
pytz==2018.4
pytzdata==2018.9
requests==2.21.0
rsa==4.0
simplejson==3.11.1
singer-python==1.5.0
sixk==1.12.0
target-bigquery==1.2.0
tzlocal==1.5.1
uritemplate==3.0.0
urllib3==1.24.1
```
